### ISSUE TITLE
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?

### ISSUE THREAD

**Issue by gabiganam** [ravsamhq/notify-slack-action#40]
Not sure what I'm doing wrong, I have 2 notifications in a specific job (start and end), the first one works fine and the second one fails with this:

`Traceback (most recent call last):
  File "/app/main.py", line 200, in <module>
    main()
  File "/app/main.py", line 195, in main
    notify_slack(payload)
  File "/app/main.py", line 169, in notify_slack
    requests.post(url, data=payload, headers=headers)
  File "/app/requests/api.py", line 117, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/app/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/app/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/app/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/app/requests/models.py", line [39](https://github.com/niio-art/one/runs/5212989943?check_suite_focus=true#step:16:39)0, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?`

The second notification is as simple as this:
`      - name: Slack notification
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          notification_title: 'Build finished'`

**Comment by apoorva11029** [comment]
@gabiganam were you able to resolve this?

**Comment by gabiganam** [comment]
Yes, it was my mistake, when copying and pasting the first action, I didn't copy the env :(
This is the error you get when you don't set the required env, maybe worth improving this with a proper error message.
